# Page settings
baseURL = "http://pitt-rssl.github.io/"
languageCode = "en-us"
title = "RSSLab @ Pitt"
theme = "business-frontpage"

[params]
    author = "University of Pittsburgh Resilient Systems and Societies Lab"
    description = "A computer systems research lab at Pitt, focusing on distributed systems and networks."

    [params.navbar]
        name = "RSSLab @ Pitt"
        url = "/"
        [[params.navbar.nav]]
        current = true
        name = "Home"
        url = "/"
        [[params.navbar.nav]]
        name = "News"
        url = "/news/"
        [[params.navbar.nav]]
        name = "People"
        url = "/people/"
        [[params.navbar.nav]]
        name = "Research"
        url = "/research/"
        [[params.navbar.nav]]
        name = "Publications"
        url = "/publications/"

    [params.header]
        name = "Resilient Systems and Societies Lab"
        tagline = "Making our societies and the infrastructure they depend on stronger through cutting-edge distributed systems research."

    [params.summary]
        url = "#"

        [params.summary.description]

        [[params.summary.description.items]]
        description = "We are a computer systems research group in the [University of Pittsburgh](https://www.pitt.edu) School of Computing and Information, with a focus on dependable infrastructure. We aim to make the networked systems our society relies on resilient to failures and attacks, and to develop new network technologies that help bring people together."

        [[params.summary.description.items]]
        description = "We conduct research on distributed systems and computer networks, aiming to not only fundamentally advance our understanding of how to design and build robust, performant systems that can be relied on to meet their requirements (despite failures and/or attacks), but also develop practical solutions with positive societal impact."


        [params.summary.contact]
        name = "RSSLab @ Pitt"
        address1 = "Information Sciences Building"
        address2 = "135 N. Bellefield Ave"
        address3 = "Pittsburgh, PA 15213"
        phone = ""
        email = "babay (at) pitt.edu"


    [params.projects]

        [[params.projects.sections]]
        title = "Active Projects"

        [[params.projects.sections.rows]]
        # title = "Section 1, Row 1"

        [[params.projects.sections.rows.items]]
        title = "Resilience to compound threats"
        description = "We are investigating how to model critical infrastructure resilience to compound threats involving natural disasters and opportunistic cyberattacks, and how to design new system architectures to better withstand these threats."
        url = "/research/compound_threats"
        # image = "image.png"

        [[params.projects.sections.rows.items]]
        title = "Intrusion tolerance as a service"
        description = "We are developing new architectures and protocols to make intrusion-tolerant systems (i.e. systems that can continue to operate correctly even while partially compromised by an attacker) easier to deploy."
        url = "/research/it_service"
        # image = "image.png"
        
        [[params.projects.sections.rows.items]]
        title = "Community-based environmental monitoring"
        description = "We are working to develop tools and socio-technical approaches to make environmental monitoring and collective sense-making of environmental data at the community level more accessible."
        url = "/research/env_monitoring"
        # image = "image.png"

        [[params.projects.sections.rows]]
        # title = "Section 1, Row 2"

        [[params.projects.sections.rows.items]]
        title = "Next-generation internet services"
        description = "We are investigating techniques to support emerging internet applications with demanding combinations of performance, reliability, and/or resilience requirements. Our current work focuses on scalable support for highly interactive applications (collaborative VR, immersive multiplayer gaming, remote manipulation)."
        url = "/research/next_gen_net"
        # image = "image.png"

    [params.footer]
        copyright = "University of Pittsburgh Resilient Systems and Societies Lab"

